import Container from "@/components/ui/Container";
import { Metadata } from "next";
import React from "react";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "123",
  description: "Generated by create next app",
};

function layout({ children }: { children: React.ReactNode }) {
  return (
    <Container>
      <Header />
      {children}
    </Container>
  );
}

export default layout;
