import Container from "@/components/ui/Container";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "123",
  description: "Generated by create next app",
};

function Header() {
  return (
    <div className="flex justify-between h-16 items-center mb-3">
      <p className="font-semibold text-2xl">Logo</p>
      <Avatar className="cursor-pointer">
        <AvatarFallback>?</AvatarFallback>
      </Avatar>
    </div>
  );
}

function layout({ children }: { children: React.ReactNode }) {
  return (
    <Container>
      <Header />
      {children}
    </Container>
  );
}

export default layout;
